---
- hosts: all
  gather_facts: false
  tasks:
    - name: set ansible_python_interpreter to python3
      set_fact:
        ansible_python_interpreter: "/usr/bin/python3"

    - name: output ansible_python_interpreter
      debug:
        var: ansible_python_interpreter

- hosts: all
  become: true
  become_user: root
  roles:
    - { role: pre-installation }