---
# If sshpass is not installed on target machine, 
# kubespray 2.11 may have these issues:
# https://github.com/kubernetes-sigs/kubespray/issues/6906
# https://github.com/kubernetes-sigs/kubespray/issues/5693
# This is resolved in PR https://github.com/kubernetes-sigs/kubespray/pull/6907
- name: "Install sshpass"
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600
    name: sshpass
    state: present
    install_recommends: no